version: '3'
services:
  app:
    image: node-template
    ports:
      - "3000:${PORT}"
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=postgres
      - TYPEORM_DATABASE=postgres
      - TYPEORM_PORT=5432

  postgres:
    image: postgres:13.0-alpine
    hostname: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - node-template-postgres13-data:/var/lib/postgresql/data
    command: -p "5432"

volumes:
  node-template-postgres13-data:
